apiVersion: v1
items:
- apiVersion: monitoring.googleapis.com/v1
  kind: PodMonitoring
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.googleapis.com/v1","kind":"PodMonitoring","metadata":{"annotations":{},"labels":{"app":"noetl-cmdbus-writer","command-bus":"ehdb","managed-by":"noetl"},"name":"noetl-cmdbus-writer","namespace":"noetl"},"spec":{"endpoints":[{"interval":"10s","path":"/metrics","port":"cmdbus-lag"},{"interval":"15s","path":"/metrics","port":"metrics"}],"selector":{"matchLabels":{"component":"cmdbus-writer"}},"targetLabels":{"metadata":["container","pod","top_level_controller_name","top_level_controller_type"]}}}
    creationTimestamp: "2026-07-27T03:53:20Z"
    generation: 1
    labels:
      app: noetl-cmdbus-writer
      command-bus: ehdb
      managed-by: noetl
    name: noetl-cmdbus-writer
    namespace: noetl
    resourceVersion: "1785459385125951007"
    uid: 69289ee9-ac4e-4e97-a86a-47a1210624f1
  spec:
    endpoints:
    - interval: 10s
      path: /metrics
      port: cmdbus-lag
    - interval: 15s
      path: /metrics
      port: metrics
    selector:
      matchLabels:
        component: cmdbus-writer
    targetLabels:
      metadata:
      - container
      - pod
      - top_level_controller_name
      - top_level_controller_type
  status:
    conditions:
    - lastTransitionTime: "2026-07-27T03:53:20Z"
      lastUpdateTime: "2026-07-27T03:53:20Z"
      status: "True"
      type: ConfigurationCreateSuccess
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
