apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"noetl-cmdbus-writer-0","command-bus":"ehdb","component":"cmdbus-writer","managed-by":"noetl","shard":"0"},"name":"noetl-cmdbus-writer-0","namespace":"noetl"},"spec":{"ports":[{"name":"cmdbus-ingest","port":9100,"targetPort":"cmdbus-ingest"},{"name":"cmdbus-claim","port":9101,"targetPort":"cmdbus-claim"},{"name":"cmdbus-lag","port":9102,"targetPort":"cmdbus-lag"},{"name":"metrics","port":9090,"targetPort":"metrics"},{"name":"events-ingest","port":9103,"targetPort":"events-ingest"},{"name":"events-claim","port":9104,"targetPort":"events-claim"},{"name":"events-sse","port":9105,"targetPort":"events-sse"},{"name":"events-lag","port":9106,"targetPort":"events-lag"}],"selector":{"app":"noetl-cmdbus-writer-0"},"type":"ClusterIP"}}
  creationTimestamp: "2026-07-27T03:53:18Z"
  labels:
    app: noetl-cmdbus-writer-0
    command-bus: ehdb
    component: cmdbus-writer
    managed-by: noetl
    shard: "0"
  name: noetl-cmdbus-writer-0
  namespace: noetl
  resourceVersion: "1785562748183311017"
  uid: a92f1bc6-948f-4022-9fc2-8eb396e5635a
spec:
  clusterIP: 34.118.233.220
  clusterIPs:
  - 34.118.233.220
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: cmdbus-ingest
    port: 9100
    protocol: TCP
    targetPort: cmdbus-ingest
  - name: cmdbus-claim
    port: 9101
    protocol: TCP
    targetPort: cmdbus-claim
  - name: cmdbus-lag
    port: 9102
    protocol: TCP
    targetPort: cmdbus-lag
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  - name: events-ingest
    port: 9103
    protocol: TCP
    targetPort: events-ingest
  - name: events-claim
    port: 9104
    protocol: TCP
    targetPort: events-claim
  - name: events-sse
    port: 9105
    protocol: TCP
    targetPort: events-sse
  - name: events-lag
    port: 9106
    protocol: TCP
    targetPort: events-lag
  - name: events-kv
    port: 9107
    protocol: TCP
    targetPort: events-kv
  - name: events-wal
    port: 9108
    protocol: TCP
    targetPort: events-wal
  selector:
    app: noetl-cmdbus-writer-0
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
