--- repos/gui/Dockerfile
+++ repos/gui/Dockerfile
@@ -4,6 +4,9 @@
 COPY package*.json ./
 RUN npm ci
 
+ARG VITE_API_MODE
+ENV VITE_API_MODE=$VITE_API_MODE
+
+ARG VITE_API_BASE_URL
+ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
+
 COPY . ./
 
 RUN npm run build
