apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    autoscaling.keda.sh/paused: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"annotations":{"autoscaling.keda.sh/paused":"true"},"labels":{"app":"noetl-worker-rust","command-bus":"ehdb","managed-by":"noetl","scaledobject.keda.sh/name":"noetl-worker-rust","worker-pool":"worker-rust-pool"},"name":"noetl-worker-rust","namespace":"noetl"},"spec":{"cooldownPeriod":30,"fallback":{"failureThreshold":3,"replicas":2},"maxReplicaCount":20,"minReplicaCount":2,"pollingInterval":10,"scaleTargetRef":{"name":"noetl-worker-rust"},"triggers":[{"metadata":{"activationTargetValue":"1","format":"prometheus","targetValue":"2","url":"http://noetl-cmdbus-writer-0.noetl.svc.cluster.local:9102/metrics","valueLocation":"ehdb_feed_total_lag"},"type":"metrics-api"},{"metadata":{"account":"$G","activationLagThreshold":"1","consumer":"noetl_worker_rust_shared","lagThreshold":"10","natsServerMonitoringEndpoint":"nats-headless.nats.svc.cluster.local:8222","stream":"NOETL_COMMANDS_RUST","useHttps":"false"},"type":"nats-jetstream"}]}}
  creationTimestamp: "2026-07-26T17:37:42Z"
  finalizers:
  - finalizer.keda.sh
  generation: 2
  labels:
    app: noetl-worker-rust
    command-bus: ehdb
    managed-by: noetl
    scaledobject.keda.sh/name: noetl-worker-rust
    worker-pool: worker-rust-pool
  name: noetl-worker-rust
  namespace: noetl
  resourceVersion: "1785459380698959000"
  uid: d803c975-0d01-449b-8b63-8363065f8709
spec:
  cooldownPeriod: 30
  fallback:
    failureThreshold: 3
    replicas: 2
  maxReplicaCount: 20
  minReplicaCount: 2
  pollingInterval: 10
  scaleTargetRef:
    name: noetl-worker-rust
  triggers:
  - metadata:
      activationTargetValue: "1"
      format: prometheus
      targetValue: "2"
      url: http://noetl-cmdbus-writer-0.noetl.svc.cluster.local:9102/metrics
      valueLocation: ehdb_feed_total_lag
    type: metrics-api
  - metadata:
      account: $G
      activationLagThreshold: "1"
      consumer: noetl_worker_rust_shared
      lagThreshold: "10"
      natsServerMonitoringEndpoint: nats-headless.nats.svc.cluster.local:8222
      stream: NOETL_COMMANDS_RUST
      useHttps: "false"
    type: nats-jetstream
status:
  conditions:
  - message: ScaledObject is defined correctly and is ready for scaling
    reason: ScaledObjectReady
    status: "True"
    type: Ready
  - message: Scaling is not performed because triggers are not active
    reason: ScalerNotActive
    status: "False"
    type: Active
  - message: No fallbacks are active on this scaled object
    reason: NoFallbackFound
    status: "False"
    type: Fallback
  - message: ScaledObject is paused
    reason: ScaledObjectPaused
    status: "True"
    type: Paused
  externalMetricNames:
  - s0-nats-jetstream-NOETL_COMMANDS_RUST
  health:
    s0-nats-jetstream-NOETL_COMMANDS_RUST:
      numberOfFailures: 0
      status: Happy
  hpaName: keda-hpa-noetl-worker-rust
  lastActiveTime: "2026-07-28T03:18:16Z"
  originalReplicaCount: 2
  scaleTargetGVKR:
    group: apps
    kind: Deployment
    resource: deployments
    version: v1
  scaleTargetKind: apps/v1.Deployment
